---
title: "Assignment1_zh2448"
output: html_document
---
0. Import the data and the packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rvest)
library(readr)
library(tidyverse)
library(ggplot2)
library(plotly)
library(stringr)
library(highcharter)
athletes <- read_csv("data/athletes_and_events.csv")
noc <- read_csv("data/noc_regions.csv")
gdppop <- read_csv("data/gdp_pop.csv")
```
1.1 Combine and clean the data
```{r}
## Filter useful variables and remove duplicate events
athletes1 <- filter(athletes, Season != "Summer") %>% 
  select(NOC, Team, Sex, Year, Sport, Event, Medal) %>%
  distinct()

## Group by countries and calculate medals and games competing in
Events <- athletes1 %>%
  group_by(NOC, Medal) %>%
  summarise(total = n())

Medal <- spread(
  Events,
  key = "Medal",
  value = "total")
colnames(Medal)[5] <- "Participate"
Medal[is.na(Medal)] <- 0
Medal <- mutate(Medal, Total =  Gold + Silver + Bronze + Participate,
                TotalMedal = Gold + Silver + Bronze) %>%
  arrange(desc(Gold))
##  Every country with different code are calculated together in sports analysis
## Sum up the same countries in different code and append gdp in gdp analysis. Reserve only those who have names in gdppop data
Medal <- right_join(noc, Medal, by = "NOC")
country <- aggregate(cbind(Gold, Silver, Bronze, TotalMedal) ~ region, data = Medal, sum)  %>%
  arrange(desc(TotalMedal))

```
1.2 Over time comparation and Medals comparation
```{r}
## Over Time table creation, the plot including 10 moat successful countries in Winter Olympics
Time <- athletes1 %>%
  group_by(NOC, Year, Medal) %>%
  summarise(total = n())
Time <- right_join(noc, Time, by = "NOC")
Time <- spread(
  Time,
  key = "Medal",
  value = "total")
Time <- Time[, -3]
Time[is.na(Time)] <- 0
Time <- mutate(Time,
              Total = Gold + Silver + Bronze) %>%
  arrange(desc(Year),desc(Gold))
top10 <- country[1:10, ]
top10overtime <- Time[Time$region %in% top10$region, ]
## Picture here with top10 countries 
library(ggthemes)
top10hc <- hchart(top10overtime, "scatter", 
       hcaes(x = Year, 
             y = Total, 
             group = region))
top10hc

Sex <- athletes1 %>%
  filter(Medal != "Na") %>%
  group_by(NOC, Sex) %>%
  summarise(total = n())

Sex <- spread(
  Sex,
  key = "Sex",
  value = "total")

Medal <- left_join(Medal, Sex, by = "NOC")
Medal$F[is.na(Medal$F)] <- 0
Medal$M[is.na(Medal$M)] <- 0
Medal <- aggregate(cbind(Gold, Silver, Bronze, TotalMedal, Participate, Total, F, M) ~ region, data = Medal, sum)  %>%
  arrange(desc(TotalMedal))
Medalsex <- mutate(Medal, genderratio = F/M)
Medalsex <- Medalsex[1:10, ]

head(Medal, 10) %>% slice

topF <- Medal %>%
  select(region, F) %>%
  arrange(desc(F))
head(topF, 10) %>% slice

topM <- Medal %>%
  select(region, M) %>%
  arrange(desc(M))
head(topM, 10) %>% slice
## The aggregated medal rank with a gender ratio perspective.
## The ratio closer to 1, the more equal for female and male to gain a medal in this country.
Medalcount <- ggplot(Medalsex, aes(x = TotalMedal, y = reorder(region, TotalMedal), size = Total)) + 
  geom_point(aes(color = genderratio)) + 
  labs(x="TotalMedal", y="region")
Medalcount
## Another pie chart of medals gained by top10 countries
Medalcount2 <- ggplot(Medalsex, 
                     aes(x = "", y = TotalMedal, fill = region)
             ) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) + 
  theme_void()
Medalcount2
```

2. GDP 
```{r}
gdp <- right_join(noc, Medal, by = "region")
gdp <- gdp[-which(gdp$notes =="Hong Kong"), ]
gdp <- inner_join(gdp, gdppop, by = c("NOC" = "Code"))
gdp <- mutate(gdp, medal_gdp = 10^3 * (Gold * 3 + Silver *2 + Bronze) / gdp$'GDP per Capita', 
              medal_pop = 10^6 * (Gold * 3 + Silver *2 + Bronze) / Population)
medal_gdp <- select(gdp, region, TotalMedal, medal_gdp) %>%
  arrange(desc(medal_gdp))
slice(medal_gdp)

medal_pop <- select(gdp, region, TotalMedal, medal_pop) %>%
  arrange(desc(medal_pop))
slice(medal_pop)
## Remove some tiny countries with <= 20 medals
medal_gdp <- medal_gdp %>%
  filter(TotalMedal > 20)
medal_pop <- medal_pop %>%
  filter(TotalMedal > 20)
gdpplot <- ggplot(medal_gdp, aes(x=reorder(region, medal_gdp), y = medal_gdp, fill = region, text = paste("Total:", TotalMedal))) +
  geom_bar(stat="identity")  + 
  coord_flip() + 
  xlab("region") + 
  ggtitle("Great Power Competition",
  subtitle = "Calculate by GDP per capita * 10^3")
ggplotly(gdpplot)

popplot <- ggplot(medal_pop, aes(x=reorder(region, medal_pop), y = medal_pop, fill = region, text = paste("Total:", TotalMedal))) +
  geom_bar(stat="identity")  + 
  coord_flip() + 
  xlab("region") + 
  ggtitle("Advantage of King in the North", 
  subtitle = "Calculate by population * 10^6")
ggplotly(popplot)
```
3.Host Country Advantage
```{r}
wiki_hosts <- read_html("https://en.wikipedia.org/wiki/List_of_Olympic_Games_host_cities")
hosts <- html_table(html_nodes(wiki_hosts, "table")[[2]], fill=TRUE)[-1]
hosts <- hosts %>% filter(Winter != "") %>%
  select(City, Country, Year)

## Modify over time df to gain meanmedals of every country
Time <- Time[, -7]
general <- Time %>% 
  select(region, Gold, Total) %>%
  group_by(region) %>%
  summarize(meanmedal = mean(Total), meangold = mean(Gold)) %>%
  arrange(desc(meanmedal))
slice(general)

##Modify host countries official names and append meanmedals
hosts$Country[hosts$Country == "United States"] <- "USA"
hosts$Country[hosts$Country == "Russia[h]"] <- "Russia"
hosts$Country[hosts$Country == "Yugoslavia"] <- "Serbia"
hostmedal <- merge(hosts, Time, by.x = c("Country", "Year"), by.y = c("region", "Year"))
hostmedal <-  hostmedal %>% 
  select(Year, Country, Gold, Total) 
hostmedal <- merge(hostmedal, general, by.x = "Country", by.y = "region")
hostmedal <- mutate(hostmedal, hostadvantage = (Total - meanmedal) * 0.7 + (Gold - meangold) * 0.3) %>%
  arrange(desc(hostadvantage))
slice(hostmedal)
## Standard of hostadvantage = (Total - meanmedal) * 0.7 + (Gold - meangold) * 0.3
## Total = Medals gained during host Olympics this time
## Gold = Gold medals gained during host Olympics this time
## meanmedal =  Medals gained during host Olympics in average
## meangold = Gold medals gained during host Olympics in average
## Based on hostadvantage to create a plotly plot
hostplot <- hostmedal %>%
  plot_ly(x = ~Year, y = ~hostadvantage) %>%
  add_lines() %>%
  layout(title = "Hostadvantage Time Series")
hostplot <- add_markers(hostplot, size = ~Total, color = ~Country)

hostplot

```
4. Most successful athletes
```{r}
athletes2 <- filter(athletes, Season != "Summer") %>%
              group_by(Name, Medal) %>%
              summarise(total = n())
success <- spread(athletes2, key = "Medal", value = "total") %>%
             arrange(desc(Gold))
success[is.na(success)] <- 0  
success <- mutate(success, total = Bronze + Silver + Gold, 
                   grade = Gold * 3 + Silver *2 + Bronze)%>%
  arrange(desc(grade))

Body <- filter(athletes, Season != "Summer") %>%
  select(Name, Sex, Height, Weight, Team) %>%
  group_by(Name, Sex, Team) %>%
  summarise(height = mean(Height), 
            weight = mean(Weight))
Body <- distinct(Body, Name, .keep_all = TRUE)
success <- inner_join(success, Body, by = "Name")
slice(success)
## standard of success = Gold * 3 + Silver *2 + Bronze
bodyplot <- success %>%
  filter(grade >= 10) %>%
  plot_ly(x = ~weight, y = ~height, type = "scatter", mode = "markers", color = ~Sex, size = ~grade, text = ~paste('Name: ', Name))

bodyplot
```
6.datatable
```{r}
library(DT)
## Medaldatatable has been ranged by Totalmedals while creating
## Countries who at least have  one particiption has been calculated
## Of course, sports is not just medals, the participation times and medals gained grouped by gender are listed in the datatable.
Medal[is.na(Medal)] <- 0
Medaldatatable <- aggregate(cbind(Gold, Silver, Bronze, TotalMedal, Participate, Total, F, M) ~ region, data = Medal, sum)  %>%
  arrange(desc(TotalMedal))
datatable(Medaldatatable,
          caption = "Table1: The aggregated medals every country has won over time",
          filter = "top") %>%
      formatStyle('region',  color = 'white', 
                backgroundColor = 'red', fontWeight = 'bold')
```